
[package]
name = "Search"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tokio = { version = "1", features = ["full"] }
rand = "0.4"
num = "0.4.0"
[dev-dependencies]
anyhow = "1"
